server:
  port: 8090

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rest_api_springboot_cloud?useTimezone=true&serverTimezone=UTC
    username: root
    password: artkou
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
springdoc:
  pathsToMatch: /api/**/v1/**
  swagger-ui:
    use-root-path: true
